### ISSUE TITLE
How do make custom opacity to the pattern

### ISSUE THREAD

**Issue by irsyadadl** [svengau/tailwindcss-hero-patterns#3]
Thanks for the great plugin you made. There are couple features we need to add into this plugin.

Since tailwind css it self has support arbitrary values, so we need the way like `heropattern-graphpaper-[red]`, not just that. This is very important, how do we define the custom opacity for the pattern ? I mean, it would be could if we can do just like this `heropattern-graphpaper-gray-800/50`. Thanks in advanced.

**Comment by mwalden2004** [comment]
This! Just downloaded but not having this is a breaker for me!

**Comment by svengau** [comment]
Hey and sorry for the late reply. I don't work on this project anymore, but feel free to push a PR, and I will merge it.
